import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClient } from "convex/browser";
import { ConvexProviderWithClerk } from "convex/react-clerk";
import ConvexClientProvider from "./ConvexClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Your Chits",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>  
    <ConvexClientProvider>
      <ClerkProvider>
      <Header/>
        { children }
      </ClerkProvider>
    </ConvexClientProvider>
      </body>
    </html> 
  );
}
